In [1]:
import pandas as pd
df_spo_wiki=pd.read_csv('./data/1_spo_wiki.csv')
df_spo_wiki.info()
df_spo_wiki.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2921 entries, 0 to 2920
Data columns (total 6 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subjectLabel    2921 non-null   object
 1   predicateLabel  2921 non-null   object
 2   objectLabel     2921 non-null   object
 3   subject         2921 non-null   object
 4   object          2921 non-null   object
 5   source          2921 non-null   object
dtypes: object(6)
memory usage: 137.0+ KB

,subjectLabel,predicateLabel,objectLabel,subject,object,source
0,pearl,has use,jewelry,Q43436,Q161439,Q83437
1,pearl,described by source,Brockhaus and Efron Encyclopedic Dictionary,Q43436,Q602358,Q83437
2,pearl,described by source,Encyclopædia Britannica 11th edition,Q43436,Q867541,Q83437
3,ruby,color,red,Q43088,Q3142,Q83437
4,nephrite,described by source,Brockhaus and Efron Encyclopedic Dictionary,Q138979,Q602358,Q83437

In [2]:
df_spo = df_spo_wiki[['subjectLabel','predicateLabel','objectLabel']]
df_spo.info()
df_spo.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2921 entries, 0 to 2920
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subjectLabel    2921 non-null   object
 1   predicateLabel  2921 non-null   object
 2   objectLabel     2921 non-null   object
dtypes: object(3)
memory usage: 68.6+ KB

,subjectLabel,predicateLabel,objectLabel
0,pearl,has use,jewelry
1,pearl,described by source,Brockhaus and Efron Encyclopedic Dictionary
2,pearl,described by source,Encyclopædia Britannica 11th edition
3,ruby,color,red
4,nephrite,described by source,Brockhaus and Efron Encyclopedic Dictionary

In [3]:
import json
def spo2kg(df_spo_wiki):
    df = df_spo_wiki
    df_spo = df_spo_wiki[['subjectLabel','predicateLabel','objectLabel']]
    
    metadata = {}
    # Base Wikipedia URL for metadata
    wiki_base_url = "https://en.wikipedia.org/wiki/"
    
    for i in df.itertuples():
        # print(i.subjectLabel)
        
        # Add subject metadata (Wikidata ID and Wikipedia URL)
        if i.subjectLabel not in metadata:
            metadata[i.subjectLabel] = {
                "url": f"{wiki_base_url}{i.subjectLabel.replace(' ', '_')}",
                "wiki_id": i.subject
            }
        
        # Add object metadata (Wikidata ID and Wikipedia URL)
        if i.objectLabel not in metadata:
            metadata[i.objectLabel] = {
                "url": f"{wiki_base_url}{i.objectLabel.replace(' ', '_')}",
                "wiki_id": i.object
            }
    
    return df_spo, metadata

df_spo, metadata = spo2kg(df_spo_wiki)
df_spo.info()
df_spo.head()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 2921 entries, 0 to 2920
Data columns (total 3 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   subjectLabel    2921 non-null   object
 1   predicateLabel  2921 non-null   object
 2   objectLabel     2921 non-null   object
dtypes: object(3)
memory usage: 68.6+ KB

,subjectLabel,predicateLabel,objectLabel
0,pearl,has use,jewelry
1,pearl,described by source,Brockhaus and Efron Encyclopedic Dictionary
2,pearl,described by source,Encyclopædia Britannica 11th edition
3,ruby,color,red
4,nephrite,described by source,Brockhaus and Efron Encyclopedic Dictionary

In [4]:
csv_file= './data/2_data.csv'
df_spo.to_csv(csv_file, header=False, index=False)
metadata_file='./data/2_metadata.json'

df_spo.to_csv(csv_file, header=False, index=False)
with open(metadata_file, 'w', encoding='utf-8') as f:
    json.dump(metadata, f, indent=2)

In [5]:
!kg add -f ./data/2_data.csv
!kg meta -f ./data/2_metadata.json
!kg start

🎉 Starting the app.
 * Serving Flask app 'kgsearch.app.app' (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: off
WARNING: This is a development server. Do not use it in a production deployment. Use a production WSGI server instead.
 * Running on http://127.0.0.1:5000
Press CTRL+C to quit
^C